travis:
  secure:
    BINSTAR_TOKEN: ModyM7dZF+EwwRFXepHQhCgppxNg56PnvzjlSauaVf7HY4rC9cF1S+bNkqR3FLnIcjCkPQm/HApT0/lywsrVZ3N0ljqdk1uENSy5YwKFNHkyp8S413mDUQos5pQmDqKuR+CkGUcBaTjoPk/4FZmkG7N+BXozwE3eoBklbqEV1vYeXefc+TcOJQqm4FlNwf61aDXHWhZ5zRIHaoYO3vch/pg7WId23lbr+NvGmkTQjAfU8W/Q1lW8AjUIY38gyhu8/5NcoGWpS1IDSv8PoLr0YGakEzKsio56f+ZdcbiDJiStKEYQzu+Xc834gOjgT/7sk76h6LTyw/5peBhW9NhxzMXr4siOTsTKQd2P6pr52EW4wFYBn6HtzwA+OFoSHcQG5PDdp2mQXX0bVy9yYzMurEY+Y2IeIm70aI4cKN9QXmNwErA5/sGQ+ZhqFQgL0IFA65qwC8uKYhJRTKiPkr8Lqggc9B5uUy04wx3v1ga1ltLUr1beuxXL4vnNoaIH+9YYUjc3Cp399Tr1wmRBv08CgX4GjLjeMeAEy6ddM4xQKhV/70jX47rnI2R1YW7KDhCpjqOgmcQtMsALtNUIH2M+TA0bk+kKyf6YxQpyMVOMZ3f6NX+j3J+J6cwAk4NWdtK8HVhm6/FokMwnIX7dqZfVjIrVPKDRpT7QazFS4cmC9Mk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
