travis:
  secure:
    BINSTAR_TOKEN: B3vJs4HBeTTLa32ok7vOcnqFcO6buFs3VkpIHnwmuq4EfZkJmL3zlxBP1nBs9SriC5stusdCoG5pyg0BHFgI/30Nf8D3W1jsz5yqney+5MfNbGxEiMD1mQfDrdWKtCSsfs2Xra5867nyLpk8dcpkY+hAfb1e0k74Ovp+jWAFYdbTZbZ4RCafo4NVoCGcOu9OY9iulFp2QQyjE9RyB93MsVpkfq5w6PeQxV8itPwaaZKmMvfYR8hbFXyWtmNQ6hLoS4WcqovusBmY/qngIyyb5LteSmXDbb59W08sxexXd/131ltThHnCGDDGH8XlFpqkYVBhT8GCeH7nLnxx9Er1+7E+0zFOTV+lSYfzCgQPDKOTuNbODplAJqQ/9sprK/hnSY3BS0gyMWtaV3+CQJAIHlIKjhk+oZ72yA9//WEV03YQH4NUvEcnjlPVsIwdU9KdmryZTSz8iZHsSm7RfxyEZj6HF7LF/V8N85iTsL/K53QBCOFZHvib39KU2fJkD1HsncCNxOq3v5GDU0NXeTLY6LqVIDqW7rTBANjaxkLf0kAZZTeS7IFgkvBRJhs4QDi/gSm5q35n6PUyAMXyxX51j1WlIyxXgNpEaQSCmXHFiFJEnPyjyWlmPBPcCsue58bMkHyaB8r2Cq1iPpxWJOX76HWQhpOX+e8+JliiKqKw8uI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
