travis:
  secure:
    BINSTAR_TOKEN: v4CzXSR3sR0X80o5Z3n7MLZfkhB6ipejQr122g+zyGPWdUQSfvZIRdmzqEmptQEs7G4eS2OilDk00ThdihKUbcPj7pXSzIvjU9rcdMJNAkFI0ogezRV6SRQcbemUrNe7Y645Bu+rpI36Yvs43Npu1SSyTDaPBOzo8K2OY5I5Qzu2lv/LjEpbmLn2VaDv8o9AYVd2fBnEOAB7rw8NAHmF4UvPEf5d4GYLBKHYa9Ig+NcoXQSfDUFDEKi3hf2fnTzxuvjlRbYkV3LUAOoa++yTgDaZBxCoDavXwz8NLm5JnemBVE1iGRD3z7QgXvaOK4rjR1XT2MkMgSIOc6QjISFbxrtDwRCsz5Km1J/ELDblyQdJvE5nkRWFHjIXtOPlnf1CUCn+TkcSVfVwAp1e7blL5dnU37PH9zZBBrbt00hG63ge6A0AmI1OGqvq+cwBXnMtn8v24d9tOpDj+Ydcpvtf/bMDG8MCFlpGQagtcoGH5rFy7pB2LLIBjDh7PSulR4lX3MI3CTK1WyGwG7qfvOVwKYvQTPjWaGielB01IVU7GZ4ggoEeQ19WMAdfASUuSYsnluV3Wt7vhQ8hX1LbwrT1RadDNHQ5BQCb8B0UcpXPXZXMjkY+O9rnfNFAkf4KVZuvl4AlwaQYD1aD4jTF8Zu06CtwFohJ4CB6nB0sBb6QBGo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
